### ISSUE TITLE
Maven-push.gradle issue in Android Studio 2.2 preview 4

### ISSUE THREAD

**Issue by tobimichigan** [realtime-framework/RealtimeMessaging-Android#29]
hi I downloaded your realtime frm https://github.com/realtime-framework/RealtimeMessaging-Android but on import into Android Studio 2.2 preview 4, but its complaining of not reading from library Error:(34, 0) Could not read script 'RealtimeMessaging-Android-master\library\maven-push.gradle' as it does not exist in the 
library\build.gradle"
any ideas?

**Comment by realtime-framework** [comment]
Fixed by https://github.com/realtime-framework/RealtimeMessaging-Android/commit/bae4ab6eece7035e90141f670d9311e6b02d021f
