### ISSUE TITLE
Client keeps disconnecting

### ISSUE THREAD

**Issue by victor5171** [realtime-framework/RealtimeMessaging-Android#35]
Hi!

My client keeps disconnecting from time to time.

I've cloned the project and looked on the stacktrace for more details.

It appears that i'm receiving the following message payload from the Realtime backend

'c[1000, "Normal closure"]'

Why the backend keeps disconnecting me? Is it a network instability?

I'm using the 2.1.72 version.

**Comment by realtime-framework** [comment]
Usually disconnections happen when there is some kind of network issue (more common in celular networks). 

Are you using client heartbeats? 
They usually improve connection stability.

(please see http://messaging-public.realtime.co/documentation/android/2.1.0/ibt/ortc/extensibility/OrtcClient.html#setHeartbeatActive-boolean-)

**Comment by victor5171** [comment]
Hi! Yes client heartbeats are activated, here is my configuration:

- **Number of fails:** 20
- **Time:** 10
- **Timeout:** 2000 miliseconds

Finally i've figured it out. This disconnections happens after i set my device to be offline (disabling wifi or enabling airplane mode) and a few seconds later reconnect it again.

After that, the backend disconnections occurs in a periodic fashion, from time to time.

Looking in the code, i've found the problem, i'm not implementing the **onReconnected** callback, and looking at the if on OrtcClient, line 1473 you can see:

`if (onReconnected != null) {
	OrtcClient sender = (OrtcClient) (args != null && args.length == 1 ? args[0]: null);
	onReconnected.run(sender);
	startHeartBeatInterval();
}`

As you can see, the startHeartBeatInterval is only called when i listen to **onReconnected** event, and because the startHeartBeatInterval is never called again, the heart beat verification fails every time.

Other problematic callback is **onConnected**, look below:

`if (onConnected != null) {
	OrtcClient sender = (OrtcClient) (args != null && args.length == 1 ? args[0] : null);
        onConnected.run(sender);
	startHeartBeatInterval();
}`

If i remove **startBeatInterval** outside the null check on both callbacks, voilá, **the problem is fixed**. :)

Can i submit a pull request?

**Comment by wmmariano** [comment]
With a question and this issue was closed?

**Comment by realtime-framework** [comment]
Sorry @wmmariano, must have pushed the wrong button, Reopening now.

**Comment by realtime-framework** [comment]
Fixed by @victor5171 pull-request. Closing now.
