### ISSUE TITLE
Client keeps disconnecting (2)

### ISSUE THREAD

**Issue by victor5171** [realtime-framework/RealtimeMessaging-Android#36]
Hi!

My client keeps disconnecting from time to time.
I've cloned the project and looked on the stacktrace for more details.
It appears that i'm receiving the following message payload from the Realtime backend

'c[1000, "Normal closure"]'

Hi! Yes client heartbeats are activated, here is my configuration:

- **Number of fails:** 20
- **Time:** 10
- **Timeout:** 2000 miliseconds

Finally i've figured it out. This disconnections happens after i set my device to be offline (disabling wifi or enabling airplane mode) and a few seconds later reconnect it again.

After that, the backend disconnections occurs in a periodic fashion, from time to time.

Looking in the code, i've found the problem, i'm not implementing the **onReconnected** callback, and looking at the if on OrtcClient, line 1473 you can see:

```java
if (onReconnected != null) {
	OrtcClient sender = (OrtcClient) (args != null && args.length == 1 ? args[0]: null);
	onReconnected.run(sender);
	startHeartBeatInterval();
}
```

As you can see, the startHeartBeatInterval is only called when i listen to **onReconnected** event, and because the startHeartBeatInterval is never called again, the heart beat verification fails every time.

Other problematic callback is **onConnected**, look below (OrtcClient, line 1394):

```java
if (onConnected != null) {
	OrtcClient sender = (OrtcClient) (args != null && args.length == 1 ? args[0] : null);
        onConnected.run(sender);
	startHeartBeatInterval();
}
```

If i put **startBeatInterval** outside the null check on both callbacks, voilá, **the problem is fixed**. :)

Can i submit a pull request?

**Comment by victor5171** [comment]
Thanks!

When you'll update the maven artifact?

**Comment by realtime-framework** [comment]
It was already released, but it may take a few minutes to be available
